{% set version = "0.10" %}

package:
  name: libblitz
  version: {{ version }}

source:
  fn: blitz-{{ version }}.tar.gz
  url: http://downloads.sourceforge.net/project/blitz/blitz/Blitz%2B%2B%20{{ version }}/blitz-{{ version }}.tar.gz
  md5: 66268b92bda923735f2e3afc87dcb58a

build:
  number: 0
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  commands:
    - test -d $PREFIX/include/blitz        # [unix]
    - test -e $PREFIX/lib/libblitz.a       # [unix]
    - test -e $PREFIX/lib/libblitz.so      # [linux]
    - test -e $PREFIX/lib/libblitz.dylib   # [osx]

about:
  home: https://sourceforge.net/projects/blitz
  license: LGPL 3
  summary: A C++ class library for scientific computing which provides performance on par with Fortran 77/90

extra:
  recipe-maintainers:
    - 183amir
