{% set version = "1.0.2" %}

package:
  name: libblitz
  version: {{ version }}

source:
  git_url: https://github.com/blitzpp/blitz.git
  git_rev: {{ version }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python
    - autoconf
    - automake
    - libtool
    - cmake  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -d $PREFIX/include/blitz        # [unix]
    - test -e $PREFIX/include/blitz/gnu/bzconfig.h  # [unix]
    - test -e $PREFIX/lib/libblitz.a       # [unix]
    - test -e $PREFIX/lib/libblitz.so      # [linux]
    - test -e $PREFIX/lib/libblitz.dylib   # [osx]
    - if not exist %PREFIX%\Library\bin\blitz.dll exit 1  # [win]
    - if not exist %PREFIX%\Library\lib\blitz.lib exit 1  # [win]
    - if not exist %PREFIX%\Library\lib\pkgconfig\blitz.pc exit 1  # [win]
    - if not exist %PREFIX%\Library\include\blitz\blitz.h exit 1  # [win]
    - if not exist %PREFIX%\Library\include\blitz\ms\bzconfig.h exit 1  # [win]

about:
  home: https://sourceforge.net/projects/blitz
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: A C++ class library for scientific computing which provides performance on par with Fortran 77/90

extra:
  recipe-maintainers:
    - 183amir
